$ANSIBLE_VAULT;1.1;AES256
36366534376335363261386365643332376238313239616530636533626139653534313031336239
6437623963396263646263373934653761633734343638630a343764383966666339353863653964
32636532306532383964336634383536633765356533316565396630363536616139353634613735
6536393239303831320a643931303231663761306134383861333463356334356562366265333439
66323063306662323131393238663533396361643162656232336631363564626438623061303136
3165323363633262633662353339343665326534393664383338