$ANSIBLE_VAULT;1.1;AES256
31396536666437323466373263336134653362333461353966653230346663643334626230376163
3961333965336366336264653236303962323837343039310a366137383636333633383835376534
64376331623562663564303231643038356230333164666532386232633236306331336535663865
3261656234616437660a306630383466656235326664626637316330303130386636633265623266
33323563343032306131373437643034353862656339373961633736306662623730353464343336
6536323637343364343462306464383762343331363833626561